### ISSUE TITLE
Wrap some elements inside div or section

### ISSUE THREAD

**Issue by haydanu** [team-d-impact-byte-batch-haku/weekend-team-project#3]
wrap all these elements inside a `<div>` or `<section> `
and give a class or id

https://github.com/team-d-impact-byte-batch-haku/Pet-Food/blob/b474a77b4b3e60310eaf5327b18b56849963f653/index.html#L79-L85

**Comment by arifinoid** [comment]
Done Mas @herdanuyp , thanks.
