### ISSUE TITLE
Change team-d-impact-byte-batch-haku to petfood

### ISSUE THREAD

**Issue by mhaidarhanif** [team-d-impact-byte-batch-haku/weekend-team-project#5]
Change `team-d-impact-byte-batch-haku` to `petfood` or something descriptive

**Comment by arifinoid** [comment]
@mhaidarh done mas, changed to https://github.com/petfood-project. thanks..

**Comment by mhaidarhanif** [comment]
Kalo issue sudah solve, bisa di-close

<img width="270" alt="Screen Shot 2019-04-02 at 15 13 45" src="https://user-images.githubusercontent.com/235584/55386552-f1482c00-5559-11e9-86d1-50772b332000.png">

<img width="211" alt="Screen Shot 2019-04-02 at 15 13 52" src="https://user-images.githubusercontent.com/235584/55386553-f1e0c280-5559-11e9-843d-3470f7b934f0.png">
